---
title: O que aconteceu com o trabalho formal? PNADC vs. RAIS
author: ~
date: '2018-08-26'
slug: trabalho-formal-2018
categories: []
tags: []
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( message = FALSE, warning = FALSE, cache = TRUE )
```

```{r pnadc_stats , message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
# define diretórios
output_dir <- "~/Bases/PNAD Contínua/Trimestral"

# cria tabela de ufs
uf <-
  structure(list(V1 = c(11L, 12L, 13L, 14L, 15L, 16L, 17L, 21L, 
                        22L, 23L, 24L, 25L, 26L, 27L, 28L, 29L, 31L, 32L, 33L, 35L, 41L, 
                        42L, 43L, 50L, 51L, 52L, 53L), 
                 V2 = structure(c(22L, 1L, 4L, 
                                  23L, 14L, 3L, 27L, 10L, 18L, 6L, 20L, 15L, 17L, 2L, 26L, 5L, 
                                  13L, 8L, 19L, 25L, 16L, 24L, 21L, 12L, 11L, 9L, 7L), 
                                .Label = c("Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", 
                                           "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", 
                                           "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", 
                                           "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", 
                                           "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", 
                                           "Tocantins"), class = "factor")), .Names = c("uf", "uf_name"), 
            class = "data.frame", row.names = c(NA, -27L))
uf$cp_name <- c("Porto Velho" , "Rio Branco" , "Manaus", "Boa Vista", "Belém", "Macapá", "Palmas", "São Luís", "Teresina", 
                "Fortaleza" , "Natal", "João Pessoa" , "Recife" , "Maceió" , "Aracaju", "Salvador", "Belo Horizonte" , 
                "Vitória" , "Rio de Janeiro", "São Paulo" , "Curitiba", "Florianópolis" , "Porto Alegre", "Campo Grande", 
                "Cuiabá", "Goiânia" , "Brasília" )
uf$rg_name <- factor( substr( uf$uf , 1 , 1 ) , levels = 1:5 , labels = c( "Norte" , "Nordeste" , "Sudeste" , "Sul" , "Centro-Oeste" ) )

# monta desenho amostral
# carrega os pacotes necessários
library( fst )
library( survey )
library( convey )
options( survey.lonely.psu = "adjust" )
options( survey.multicore = TRUE )

# list files
these_designs <- list.files( output_dir , full.names = TRUE , pattern = "fst" )
these_designs <- these_designs[ grepl( "02\\.fst$", these_designs ) ]
# this_file <- these_designs[[1]] 

# select columns
these_columns <- c( "upa" , "estrato" , "v1027" , "posest" , "v1029" , "ano" , "trimestre" , "uf" , "vd4001" , "vd4002" , "vd4003" , "vd4007" , "vd4008" , "vd4009" , "v2009" )

# loop through files
pnadc_stats <- plyr::llply ( these_designs , function( this_file ) {
  
  # read data
  pnadc_df <- read_fst( this_file , columns = these_columns )
  
  # get time ref
  this_year <- pnadc_df$ano[[1]]
  this_quarter <- pnadc_df$trimestre[[1]]
  
  # merge data
  pnadc_df <- merge( pnadc_df , uf , by = "uf" )
  
  # add one column
  pnadc_df$one <- 1
  
  # create region
  pnadc_df$regiao <- substr( pnadc_df$uf , 1 , 1 )
  pnadc_df$regiao <- factor( pnadc_df$regiao , labels = c( "Norte", "Nordeste" , "Sudeste" , "Sul" , "Centro-Oeste" ) )
  
  # create new variables
  pnadc_df$vd4009a <- ifelse( pnadc_df$vd4009 %in% c(1,3,5) , "Trabalhador com carteira assinada" , 
                              ifelse( pnadc_df$vd4009 %in% c(2,4,6) , "Trabalhador sem carteira assinada" ,
                                      ifelse( pnadc_df$vd4009 %in% 7 , "Militares e estatutários"  ,
                                              ifelse( pnadc_df$vd4009 %in% 8 , "Empregador" ,
                                                      ifelse( pnadc_df$vd4009 %in% 9 , "Conta própria" ,
                                                              ifelse( pnadc_df$vd4009 %in% 10 , "Trabalhador familiar auxiliar" , NA ) ) ) ) ) )
  
  # create labels
  pnadc_df$vd4001 <- factor( pnadc_df$vd4001 , labels = c("Pessoas na força de trabalho", "Pessoas fora da força de trabalho" ) )
  pnadc_df$vd4002 <- factor( pnadc_df$vd4002 , labels = c( "Pessoas ocupadas", "Pessoas desocupadas" ) )
  pnadc_df$vd4003 <- factor( pnadc_df$vd4003 , labels = c( "Pessoas fora da força de trabalho e na força de trabalho potencial" , "Pessoas fora da força de trabalho e fora da força de trabalho potencial" ) )
  pnadc_df$vd4007 <- factor( pnadc_df$vd4007 , labels = c( "Empregado (inclusive trabalhador doméstico)", "Empregador", "Conta própria", "Trabalhador familiar auxiliar" ) )
  pnadc_df$vd4008 <- factor( pnadc_df$vd4008 , labels = c( "Empregado no setor privado" , "Trabalhador doméstico" , "Empregado no setor público (inclusive servidor estatutário e militar)", "Empregador" , "Conta-própria" , "Trabalhador familiar auxiliar"
  ) )
   pnadc_df$vd4009 <- factor( pnadc_df$vd4009 , labels = c( "Empregado no setor privado com carteira de trabalho assinada" , "Empregado no setor privado sem carteira de trabalho assinada" , "Trabalhador doméstico com carteira de trabalho assinada" , "Trabalhador doméstico sem carteira de trabalho assinada" , "Empregado no setor público com carteira de trabalho assinada" , "Empregado no setor público sem carteira de trabalho assinada" , "Militar e servidor estatutário" , "Empregador" , "Conta-própria" , "Trabalhador familiar auxiliar" ) )

  
  # preliminary survey design
  pre_stratified <-
    svydesign(
      ids = ~ upa , 
      strata = ~ estrato , 
      weights = ~ v1027 , 
      data = pnadc_df ,
      nest = TRUE
    )
  # warning: do not use `pre_stratified` in your analyses!
  # you must use the `pnadc_design` object created below.
  
  # post-stratification targets
  df_pos <- data.frame( posest = unique( pnadc_df$posest ) , Freq = unique( pnadc_df$v1029 ) )
  
  # final survey design object
  pnadc_design <- postStratify( pre_stratified , ~ posest , df_pos )
  
  # remove the `pnadc_df` data.frame object
  # and the `pre_stratified` design before stratification
  rm( pnadc_df , pre_stratified , df_pos )
  
  
  # emprego formal
  pnadc_tots <- svytotal( ~vd4009a , pnadc_design , na.rm = TRUE )
  pnadc_perc <- svymean( ~vd4009a , pnadc_design , na.rm = TRUE )
  
  # return list
  list( this_year , this_quarter , pnadc_tots , pnadc_perc )
  
} , .progress = "text" )

```
